apiVersion: v2
name: rancher-csp-adapter
description: Cloud Service Provider Marketplace Adapter for Rancher. Monitors Rancher entitlements against usage.
version: 999
appVersion: 999
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-csp-adapter-system
  catalog.cattle.io/release-name: rancher-csp-adapter
  catalog.cattle.io/display-name: "Rancher CSP Adapter"
  catalog.cattle.io/scope: management
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.9.0-0'
  catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'
